/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaskedua;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class framepertama extends javax.swing.JFrame {
    public int jumlahjam,tarifjam,gajibruto,jamlembur,gajilembur,pajak,gajibersih;

    /**
     * Creates new form framepertama
     */
    public framepertama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jumlah = new javax.swing.JLabel();
        tarif = new javax.swing.JLabel();
        bruto = new javax.swing.JLabel();
        bersih = new javax.swing.JLabel();
        eJumlah = new javax.swing.JTextField();
        eTarif = new javax.swing.JTextField();
        eBruto = new javax.swing.JTextField();
        eBersih = new javax.swing.JTextField();
        hitungBruto = new javax.swing.JButton();
        hitungBersih = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eHapus = new javax.swing.JButton();
        eSimpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Limelight", 1, 24)); // NOI18N
        jLabel1.setText("GAJI KARYAWAN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 6, 238, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugaskedua/gambarsatu.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 380, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jumlah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jumlah.setText("JUMLAH JAM KERJA");
        jPanel3.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, -1, -1));

        tarif.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tarif.setText("TARIF KERJA");
        jPanel3.add(tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));

        bruto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bruto.setText("GAJI BRUTO");
        jPanel3.add(bruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        bersih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bersih.setText("GAJI BERSIH");
        jPanel3.add(bersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        eJumlah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(eJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 6, 130, -1));

        eTarif.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(eTarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 39, 130, -1));

        eBruto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(eBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 197, -1));

        eBersih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(eBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 196, -1));

        hitungBruto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hitungBruto.setText("HITUNG GAJI BRUTO");
        hitungBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBrutoActionPerformed(evt);
            }
        });
        jPanel3.add(hitungBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        hitungBersih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hitungBersih.setText("HITUNG GAJI BERSIH");
        hitungBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBersihActionPerformed(evt);
            }
        });
        jPanel3.add(hitungBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("/MINGGU");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("/JAM");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 43, 30));

        eHapus.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        eHapus.setText("HAPUS");
        eHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eHapusActionPerformed(evt);
            }
        });
        jPanel3.add(eHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        eSimpan.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        eSimpan.setText("SIMPAN");
        eSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(eSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugaskedua/gambarsatu.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 380, 270));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBersihActionPerformed
        pajak = (int)(0.1 * gajibruto);
        gajibersih = gajibruto - pajak;
        eBersih.setText(String.valueOf(gajibersih));
    }//GEN-LAST:event_hitungBersihActionPerformed

    private void hitungBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBrutoActionPerformed
         jumlahjam = Integer.parseInt(eJumlah.getText());
         tarifjam = Integer.parseInt(eTarif.getText());
        if (jumlahjam <= 40){
            gajibruto = jumlahjam * tarifjam;
        }
        else {
            jamlembur = jumlahjam - 40;
            gajilembur = (int)(jamlembur * (tarifjam * 1.5));
            gajibruto = 40 * tarifjam + gajilembur;
        }
        eBruto.setText(String.valueOf(gajibruto));
    }//GEN-LAST:event_hitungBrutoActionPerformed

    private void eHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eHapusActionPerformed
        eJumlah.setText(""); 
        eTarif.setText("");
        eBruto.setText("");
        eBersih.setText("");
    }//GEN-LAST:event_eHapusActionPerformed

    private void eSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eSimpanActionPerformed
//        int jumlahjam,tarifjam,gajibruto,gajibersih;
        jumlahjam = Integer.parseInt(eJumlah.getText());
        tarifjam = Integer.parseInt(eTarif.getText());
        gajibruto = Integer.parseInt(eBruto.getText());
        gajibersih = Integer.parseInt(eBersih.getText());
        
        JOptionPane.showMessageDialog(this, "JUMLAH JAM KERJA: " + jumlahjam 
            + "\nTARIF KERJA: " + tarifjam  
            + "\nGAJI BRUTO: " + gajibruto 
            + "\nGAJI BERSIH: " + gajibersih );
                
        eJumlah.setText(""); 
        eTarif.setText("");
        eBruto.setText("");
        eBersih.setText("");
    }//GEN-LAST:event_eSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framepertama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framepertama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framepertama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framepertama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framepertama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bersih;
    private javax.swing.JLabel bruto;
    private javax.swing.JTextField eBersih;
    private javax.swing.JTextField eBruto;
    private javax.swing.JButton eHapus;
    private javax.swing.JTextField eJumlah;
    private javax.swing.JButton eSimpan;
    private javax.swing.JTextField eTarif;
    private javax.swing.JButton hitungBersih;
    private javax.swing.JButton hitungBruto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel tarif;
    // End of variables declaration//GEN-END:variables
}
